# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPMLeOMn_g0kmtRwWgV7KTtkatRuDuC0

<h1 align='center' style='color:purple'>Clustering With K Means - Python Tutorial</h1>
"""


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Customer Segmentation using K-Means",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Customer Segmentation using K-Means Clustering")
st.write("This application groups customers based on their Age and Annual Income.")

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("income.csv")

# Rename if necessary
# Make sure these match your dataset column names
X = df[['Age', 'Income($)']]

# -----------------------------
# Scale Data
# -----------------------------
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# -----------------------------
# Train KMeans Model
# -----------------------------
model = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["Cluster"] = model.fit_predict(X_scaled)

# -----------------------------
# Sidebar Inputs
# -----------------------------
st.sidebar.header("Enter Customer Details")

age = st.sidebar.slider(
    "Age",
    int(df["Age"].min()),
    int(df["Age"].max()),
    30
)

income = st.sidebar.slider(
    "Income",
    int(df["Income($)"].min()),
    int(df["Income($)"].max()),
    50000
)

# -----------------------------
# Prediction
# -----------------------------
input_data = scaler.transform([[age, income]])
cluster = model.predict(input_data)[0]

st.success(f"Predicted Cluster: **{cluster}**")

# -----------------------------
# Cluster Centers
# -----------------------------
st.subheader("Cluster Centers")

centers = scaler.inverse_transform(model.cluster_centers_)

centers_df = pd.DataFrame(
    centers,
    columns=["Age", "Income"]
)

st.dataframe(centers_df)

# -----------------------------
# Scatter Plot
# -----------------------------
st.subheader("Customer Clusters")

fig, ax = plt.subplots(figsize=(8,6))

colors = ['red', 'green', 'blue']

for i in range(3):
    cluster_data = df[df["Cluster"] == i]

    ax.scatter(
        cluster_data["Age"],
        cluster_data["Income($)"],
        color=colors[i],
        label=f"Cluster {i}"
    )

# User point
ax.scatter(
    age,
    income,
    color="black",
    marker="*",
    s=250,
    label="Your Input"
)

ax.set_xlabel("Age")
ax.set_ylabel("Income")
ax.legend()

st.pyplot(fig)

# -----------------------------
# Elbow Method
# -----------------------------
st.subheader("Elbow Method")

sse = []

for k in range(1,11):
    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    km.fit(X_scaled)
    sse.append(km.inertia_)

fig2, ax2 = plt.subplots(figsize=(7,4))

ax2.plot(range(1,11), sse, marker='o')

ax2.set_xlabel("Number of Clusters")
ax2.set_ylabel("SSE")
ax2.set_title("Elbow Method")

st.pyplot(fig2)

# -----------------------------
# Cluster Distribution
# -----------------------------
st.subheader("Cluster Distribution")

cluster_count = df["Cluster"].value_counts().sort_index()

st.bar_chart(cluster_count)

# -----------------------------
# Dataset
# -----------------------------
st.subheader("Dataset")

st.dataframe(df)

# -----------------------------
# Download Dataset
# -----------------------------
csv = df.to_csv(index=False)

st.download_button(
    label="Download Clustered Dataset",
    data=csv,
    file_name="clustered_dataset.csv",
    mime="text/csv"
)
